In [39]:
import pandas as pd

In [40]:
df= pd.read_csv("C:\\Users\\Arpit\\Downloads\\patients.csv")

In [41]:
df.head()

patient_id assigned_sex given_name  surname                    address  \
0           1       female        Zoe  Wellish       576 Brown Bear Drive   
1           2       female     Pamela     Hill  2370 University Hill Road   
2           3         male        Jae   Debord      1493 Poling Farm Road   
3           4         male       Liêm     Phan        2335 Webster Street   
4           5         male        Tim  Neudorf       1428 Turkey Pen Lane   

                city       state  zip_code        country  \
0  Rancho California  California   92390.0  United States   
1          Armstrong    Illinois   61812.0  United States   
2               York    Nebraska   68467.0  United States   
3         Woodbridge          NJ    7095.0  United States   
4             Dothan          AL   36303.0  United States   

                                      contact  birthdate  weight  height   bmi  
0        951-719-9170ZoeWellish@superrito.com  7/10/1976   121.7      66  19.6  
1       PamelaSHill@cuvox.de+1 (217) 569-3204   4/3/1967   118.8      66  19.2  
2            402-363-6804JaeMDebord@gustr.com  2/19/1980   177.8      71  24.8  
3  PhanBaLiem@jourrapide.com+1 (732) 636-8246  7/26/1951   220.9      70  31.7  
4             334-515-7487TimNeudorf@cuvox.de  2/18/1928   192.3      27  26.1

In [42]:
df.isnull().mean()*100

patient_id      0.000000
assigned_sex    0.000000
given_name      0.000000
surname         0.000000
address         2.385686
city            2.385686
state           2.385686
zip_code        2.385686
country         2.385686
contact         2.385686
birthdate       0.000000
weight          0.000000
height          0.000000
bmi             0.000000
dtype: float64

In [43]:
col = [var for var in df.columns if df[var].isnull().mean()<0.5 and df[var].isnull().mean() > 0]

In [44]:
df[col].sample(5)

address          city     state  zip_code        country  \
364          4704 Edsel Road  Sherman Oaks        CA   91403.0  United States   
121  1845 Saint Marys Avenue      Syracuse  New York   13221.0  United States   
105      4310 Johnson Street       Clinton        NC   28328.0  United States   
307      4168 Coventry Court      Gulfport        MS   39501.0  United States   
467          1557 Byers Lane       Redding        CA   96001.0  United States   

                                         contact  
364  818-372-7106ChukwumogeOgochukwu@teleworm.us  
121     FrydrykAdamski@armyspy.com1 315 869 4408  
105            NateBowden@einrot.com919-915-8670  
307         228-237-2271MatheaLilleb@fleckens.hu  
467     530-773-9263JozkaResanovic@superrito.com

In [45]:
len(df[col].dropna())/len(df)

0.9761431411530815

In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [47]:
data = pd.read_csv("C:\\Users\\Arpit\\Downloads\\train (2).csv", usecols=['Age', 'Fare', 'Survived'])


In [48]:
data.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [49]:
data.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [50]:
X =data.drop(columns=['Survived'])
y = data['Survived']

In [51]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [52]:
X_train['Age_imp'] = X_train['Age']
X_test['Age_imp'] = X_test['Age']

In [53]:
# For X_train
X_train.loc[X_train['Age_imp'].isnull(), 'Age_imp'] = X_train['Age'].dropna().sample(
    X_train['Age_imp'].isnull().sum(), replace=True).values

# For X_test
X_test.loc[X_test['Age_imp'].isnull(), 'Age_imp'] = X_train['Age'].dropna().sample(
    X_test['Age_imp'].isnull().sum(), replace=True).values


In [54]:
X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values

array([ 3.  , 62.  ,  2.  , 32.  , 45.  , 18.  , 28.5 , 21.  , 19.  ,
       23.  , 50.  , 58.  , 18.  , 40.  , 36.  , 20.  , 32.  , 36.  ,
       45.  , 24.  , 18.  , 35.  , 26.  , 24.  , 19.  , 45.  , 36.  ,
       20.  , 29.  , 32.  ,  0.42, 52.  , 25.  ,  0.83, 31.  , 31.  ,
       31.  , 29.  , 23.  ,  2.  , 32.  , 16.  , 22.  , 30.  , 22.  ,
       30.5 , 45.  , 45.  , 35.  , 38.  , 22.  ,  9.  , 43.  , 15.  ,
       33.  , 16.  , 30.  , 18.  ,  4.  , 31.  , 22.  , 38.  , 25.  ,
       28.  , 31.  , 32.  , 23.  , 24.  , 12.  , 36.  , 33.  , 19.  ,
       34.  , 65.  , 24.  , 21.  , 24.  , 17.  ,  6.  , 44.  , 24.  ,
       35.  ,  9.  , 49.  , 14.  ,  9.  , 36.  , 45.  , 26.  , 24.  ,
       24.  , 32.  , 35.  , 22.  , 31.  , 36.  , 28.  , 10.  , 33.  ,
       41.  , 22.  , 21.  , 47.  , 14.  ,  2.  , 48.  , 26.  , 37.  ,
        5.  , 57.  , 21.  , 31.  , 36.  , 46.  , 45.5 , 35.  , 37.  ,
        7.  , 25.  , 31.  , 56.  , 26.  , 22.  , 24.  , 45.5 , 27.  ,
       16.  , 31.  ,

In [56]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [57]:
df4 = pd.read_csv("C:\\Users\\Arpit\\Downloads\\train (2).csv", usecols=['Age', 'Fare', 'Survived'])

In [58]:
df4.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [59]:
df4.sample(5)

Survived   Age     Fare
620         0  27.0  14.4542
296         0  23.5   7.2292
158         0   NaN   8.6625
806         0  39.0   0.0000
392         0  28.0   7.9250

In [60]:
X =data.drop(columns=['Survived'])
y = data['Survived']

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [66]:
X_train

Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [67]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf= si.fit_transform(X_test)

In [68]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [73]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred = clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [75]:
mi = MissingIndicator()
mi.fit(X_train)

MissingIndicator()

In [76]:
 MissingIndicator()

MissingIndicator()

In [77]:
mi.features_

array([0], dtype=int64)

In [78]:
X_train_miss = mi.transform(X_train)

In [79]:
X_train_miss

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [80]:
X_test_miss = mi.transform(X_test)

In [91]:
X_test['Age_Na'] = X_test_miss

In [82]:
X_train

Age      Fare  Age_Na
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [92]:

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [94]:

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_trf2,y_train)
y_pred = clf.predict(X_test_trf2)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173